# Generated by Django 5.0.1 on 2024-08-10 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classroom", "0005_attendance"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("obtained_marks", models.PositiveIntegerField()),
                ("full_marks", models.PositiveIntegerField()),
                ("percentage", models.PositiveIntegerField(blank=True, null=True)),
                ("mid_term", models.BooleanField(default=False)),
                ("pre_board", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="classroom.subject",
                    ),
                ),
            ],
            options={
                "db_table": "exam_results",
                "unique_together": {("student", "subject", "mid_term", "pre_board")},
            },
        ),
    ]
